const ADD_FAVORITE_GIF = 'gif/ADD_FAVORITE_GIF';
const REMOVE_FAVORITE_GIF = 'gif/REMOVE_FAVORITE_GIF';
const UPDATE_FAVORITE_GIF = 'gif/UPDATE_FAVORITE_GIF';
const VIEW_FAVORITES = 'gif/VIEW_FAVORITES';

export {
  ADD_FAVORITE_GIF,
  REMOVE_FAVORITE_GIF,
  UPDATE_FAVORITE_GIF,
  VIEW_FAVORITES,
}; 